name: CI Test and Validation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for PR checks

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting & linting
        run: pnpm check

      - name: Check TypeScript types
        run: pnpm build --noEmit

      - name: Run tests
        id: tests
        run: pnpm test
      
      # Report test status to PR
      - name: Report test status
        if: always() && github.event_name == 'pull_request'
        run: |
          if [ "${{ steps.tests.outcome }}" == "success" ]; then
            echo "Tests passed successfully! ✅"
          else
            echo "Tests failed! ❌"
            exit 1
          fi